# Generated by Django 5.0.3 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_avatar_profile_profile_picture_profile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(blank=True, related_name="followers", to="accounts.profile"),
        ),
    ]
